[package]
name = "shogg_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand = "0.8"
ts-rs = { version = "10", features = ["serde-json-impl"] }
